[1mdiff --git a/.gitignore b/.gitignore[m
[1mindex 6704566..02f6e50 100644[m
[1m--- a/.gitignore[m
[1m+++ b/.gitignore[m
[36m@@ -1,104 +1,19 @@[m
[31m-# Logs[m
[31m-logs[m
[31m-*.log[m
[31m-npm-debug.log*[m
[31m-yarn-debug.log*[m
[31m-yarn-error.log*[m
[31m-lerna-debug.log*[m
[31m-[m
[31m-# Diagnostic reports (https://nodejs.org/api/report.html)[m
[31m-report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json[m
[31m-[m
[31m-# Runtime data[m
[31m-pids[m
[31m-*.pid[m
[31m-*.seed[m
[31m-*.pid.lock[m
[31m-[m
[31m-# Directory for instrumented libs generated by jscoverage/JSCover[m
[31m-lib-cov[m
[31m-[m
[31m-# Coverage directory used by tools like istanbul[m
[31m-coverage[m
[31m-*.lcov[m
[31m-[m
[31m-# nyc test coverage[m
[31m-.nyc_output[m
[32m+[m[32m# build output[m
[32m+[m[32mdist/[m
 [m
[31m-# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)[m
[31m-.grunt[m
[31m-[m
[31m-# Bower dependency directory (https://bower.io/)[m
[31m-bower_components[m
[31m-[m
[31m-# node-waf configuration[m
[31m-.lock-wscript[m
[31m-[m
[31m-# Compiled binary addons (https://nodejs.org/api/addons.html)[m
[31m-build/Release[m
[31m-[m
[31m-# Dependency directories[m
[32m+[m[32m# dependencies[m
 node_modules/[m
[31m-jspm_packages/[m
[31m-[m
[31m-# TypeScript v1 declaration files[m
[31m-typings/[m
[31m-[m
[31m-# TypeScript cache[m
[31m-*.tsbuildinfo[m
[31m-[m
[31m-# Optional npm cache directory[m
[31m-.npm[m
 [m
[31m-# Optional eslint cache[m
[31m-.eslintcache[m
[31m-[m
[31m-# Microbundle cache[m
[31m-.rpt2_cache/[m
[31m-.rts2_cache_cjs/[m
[31m-.rts2_cache_es/[m
[31m-.rts2_cache_umd/[m
[31m-[m
[31m-# Optional REPL history[m
[31m-.node_repl_history[m
[31m-[m
[31m-# Output of 'npm pack'[m
[31m-*.tgz[m
[32m+[m[32m# logs[m
[32m+[m[32mnpm-debug.log*[m
[32m+[m[32myarn-debug.log*[m
[32m+[m[32myarn-error.log*[m
[32m+[m[32mpnpm-debug.log*[m
 [m
[31m-# Yarn Integrity file[m
[31m-.yarn-integrity[m
 [m
[31m-# dotenv environment variables file[m
[32m+[m[32m# environment variables[m
 .env[m
[31m-.env.test[m
[31m-[m
[31m-# parcel-bundler cache (https://parceljs.org/)[m
[31m-.cache[m
[31m-[m
[31m-# Next.js build output[m
[31m-.next[m
[31m-[m
[31m-# Nuxt.js build / generate output[m
[31m-.nuxt[m
[31m-dist[m
[31m-[m
[31m-# Gatsby files[m
[31m-.cache/[m
[31m-# Comment in the public line in if your project uses Gatsby and *not* Next.js[m
[31m-# https://nextjs.org/blog/next-9-1#public-directory-support[m
[31m-# public[m
[31m-[m
[31m-# vuepress build output[m
[31m-.vuepress/dist[m
[31m-[m
[31m-# Serverless directories[m
[31m-.serverless/[m
[31m-[m
[31m-# FuseBox cache[m
[31m-.fusebox/[m
[31m-[m
[31m-# DynamoDB Local files[m
[31m-.dynamodb/[m
[32m+[m[32m.env.production[m
 [m
[31m-# TernJS port file[m
[31m-.tern-port[m
[32m+[m[32m# macOS-specific files[m
[32m+[m[32m.DS_Store[m
[1mdiff --git a/README.md b/README.md[m
[1mindex 70891ce..234bc15 100644[m
[1m--- a/README.md[m
[1m+++ b/README.md[m
[36m@@ -1 +1,29 @@[m
[31m-# portfolio-astro[m
\ No newline at end of file[m
[32m+[m[32m# Astro Starter Kit: Portfolio[m
[32m+[m
[32m+[m[32m```[m
[32m+[m[32mnpm init astro -- --template portfolio[m
[32m+[m[32m```[m
[32m+[m
[32m+[m[32m[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/github/withastro/astro/tree/latest/examples/portfolio)[m
[32m+[m
[32m+[m[32m> 🧑‍🚀 **Seasoned astronaut?** Delete this file. Have fun![m
[32m+[m
[32m+[m[32m![portfolio](https://user-images.githubusercontent.com/4677417/186189473-03dda103-65d3-4220-8b60-180ccaee5939.png)[m
[32m+[m
[32m+[m
[32m+[m[32m## 🧞 Commands[m
[32m+[m
[32m+[m[32mAll commands are run from the root of the project, from a terminal:[m
[32m+[m
[32m+[m[32m| Command                | Action                                           |[m
[32m+[m[32m| :--------------------- | :----------------------------------------------- |[m
[32m+[m[32m| `npm install`          | Installs dependencies                            |[m
[32m+[m[32m| `npm run dev`          | Starts local dev server at `localhost:3000`      |[m
[32m+[m[32m| `npm run build`        | Build your production site to `./dist/`          |[m
[32m+[m[32m| `npm run preview`      | Preview your build locally, before deploying     |[m
[32m+[m[32m| `npm run astro ...`    | Run CLI commands like `astro add`, `astro check` |[m
[32m+[m[32m| `npm run astro --help` | Get help using the Astro CLI                     |[m
[32m+[m
[32m+[m[32m## 👀 Want to learn more?[m
[32m+[m
[32m+[m[32mFeel free to check [our documentation](https://docs.astro.build) or jump into our [Discord server](https://astro.build/chat).[m
